package proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

public final class MsgInfo {
  private MsgInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Msg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string topic = 2;</code>
     * @return The topic.
     */
    java.lang.String getTopic();
    /**
     * <code>string topic = 2;</code>
     * @return The bytes for topic.
     */
    com.google.protobuf.ByteString
        getTopicBytes();

    /**
     * <code>bytes content = 3;</code>
     * @return The content.
     */
    com.google.protobuf.ByteString getContent();

    /**
     * <code>string senderName = 4;</code>
     * @return The senderName.
     */
    java.lang.String getSenderName();
    /**
     * <code>string senderName = 4;</code>
     * @return The bytes for senderName.
     */
    com.google.protobuf.ByteString
        getSenderNameBytes();

    /**
     * <code>int32 senderId = 5;</code>
     * @return The senderId.
     */
    int getSenderId();

    /**
     * <code>string type = 6;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <code>string type = 6;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>int32 startingPosition = 7;</code>
     * @return The startingPosition.
     */
    int getStartingPosition();

    /**
     * <code>int32 requiredMsgCount = 8;</code>
     * @return The requiredMsgCount.
     */
    int getRequiredMsgCount();

    /**
     * <code>int32 copyNum = 9;</code>
     * @return The copyNum.
     */
    int getCopyNum();

    /**
     * <code>int32 leaderId = 10;</code>
     * @return The leaderId.
     */
    int getLeaderId();

    /**
     * <code>string dataVersion = 11;</code>
     * @return The dataVersion.
     */
    java.lang.String getDataVersion();
    /**
     * <code>string dataVersion = 11;</code>
     * @return The bytes for dataVersion.
     */
    com.google.protobuf.ByteString
        getDataVersionBytes();

    /**
     * <code>string subscriber = 12;</code>
     * @return The subscriber.
     */
    java.lang.String getSubscriber();
    /**
     * <code>string subscriber = 12;</code>
     * @return The bytes for subscriber.
     */
    com.google.protobuf.ByteString
        getSubscriberBytes();

    /**
     * <code>string topic1Owner = 13;</code>
     * @return The topic1Owner.
     */
    java.lang.String getTopic1Owner();
    /**
     * <code>string topic1Owner = 13;</code>
     * @return The bytes for topic1Owner.
     */
    com.google.protobuf.ByteString
        getTopic1OwnerBytes();

    /**
     * <code>string topic2Owner = 14;</code>
     * @return The topic2Owner.
     */
    java.lang.String getTopic2Owner();
    /**
     * <code>string topic2Owner = 14;</code>
     * @return The bytes for topic2Owner.
     */
    com.google.protobuf.ByteString
        getTopic2OwnerBytes();
  }
  /**
   * Protobuf type {@code Msg}
   */
  public static final class Msg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Msg)
      MsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Msg.newBuilder() to construct.
    private Msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Msg() {
      topic_ = "";
      content_ = com.google.protobuf.ByteString.EMPTY;
      senderName_ = "";
      type_ = "";
      dataVersion_ = "";
      subscriber_ = "";
      topic1Owner_ = "";
      topic2Owner_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Msg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              topic_ = s;
              break;
            }
            case 26: {

              content_ = input.readBytes();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              senderName_ = s;
              break;
            }
            case 40: {

              senderId_ = input.readInt32();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 56: {

              startingPosition_ = input.readInt32();
              break;
            }
            case 64: {

              requiredMsgCount_ = input.readInt32();
              break;
            }
            case 72: {

              copyNum_ = input.readInt32();
              break;
            }
            case 80: {

              leaderId_ = input.readInt32();
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              dataVersion_ = s;
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              subscriber_ = s;
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              topic1Owner_ = s;
              break;
            }
            case 114: {
              java.lang.String s = input.readStringRequireUtf8();

              topic2Owner_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MsgInfo.internal_static_Msg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MsgInfo.internal_static_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MsgInfo.Msg.class, MsgInfo.Msg.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int TOPIC_FIELD_NUMBER = 2;
    private volatile java.lang.Object topic_;
    /**
     * <code>string topic = 2;</code>
     * @return The topic.
     */
    @java.lang.Override
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      }
    }
    /**
     * <code>string topic = 2;</code>
     * @return The bytes for topic.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>bytes content = 3;</code>
     * @return The content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    public static final int SENDERNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object senderName_;
    /**
     * <code>string senderName = 4;</code>
     * @return The senderName.
     */
    @java.lang.Override
    public java.lang.String getSenderName() {
      java.lang.Object ref = senderName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderName_ = s;
        return s;
      }
    }
    /**
     * <code>string senderName = 4;</code>
     * @return The bytes for senderName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSenderNameBytes() {
      java.lang.Object ref = senderName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERID_FIELD_NUMBER = 5;
    private int senderId_;
    /**
     * <code>int32 senderId = 5;</code>
     * @return The senderId.
     */
    @java.lang.Override
    public int getSenderId() {
      return senderId_;
    }

    public static final int TYPE_FIELD_NUMBER = 6;
    private volatile java.lang.Object type_;
    /**
     * <code>string type = 6;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 6;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STARTINGPOSITION_FIELD_NUMBER = 7;
    private int startingPosition_;
    /**
     * <code>int32 startingPosition = 7;</code>
     * @return The startingPosition.
     */
    @java.lang.Override
    public int getStartingPosition() {
      return startingPosition_;
    }

    public static final int REQUIREDMSGCOUNT_FIELD_NUMBER = 8;
    private int requiredMsgCount_;
    /**
     * <code>int32 requiredMsgCount = 8;</code>
     * @return The requiredMsgCount.
     */
    @java.lang.Override
    public int getRequiredMsgCount() {
      return requiredMsgCount_;
    }

    public static final int COPYNUM_FIELD_NUMBER = 9;
    private int copyNum_;
    /**
     * <code>int32 copyNum = 9;</code>
     * @return The copyNum.
     */
    @java.lang.Override
    public int getCopyNum() {
      return copyNum_;
    }

    public static final int LEADERID_FIELD_NUMBER = 10;
    private int leaderId_;
    /**
     * <code>int32 leaderId = 10;</code>
     * @return The leaderId.
     */
    @java.lang.Override
    public int getLeaderId() {
      return leaderId_;
    }

    public static final int DATAVERSION_FIELD_NUMBER = 11;
    private volatile java.lang.Object dataVersion_;
    /**
     * <code>string dataVersion = 11;</code>
     * @return The dataVersion.
     */
    @java.lang.Override
    public java.lang.String getDataVersion() {
      java.lang.Object ref = dataVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string dataVersion = 11;</code>
     * @return The bytes for dataVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDataVersionBytes() {
      java.lang.Object ref = dataVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBSCRIBER_FIELD_NUMBER = 12;
    private volatile java.lang.Object subscriber_;
    /**
     * <code>string subscriber = 12;</code>
     * @return The subscriber.
     */
    @java.lang.Override
    public java.lang.String getSubscriber() {
      java.lang.Object ref = subscriber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subscriber_ = s;
        return s;
      }
    }
    /**
     * <code>string subscriber = 12;</code>
     * @return The bytes for subscriber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSubscriberBytes() {
      java.lang.Object ref = subscriber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subscriber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOPIC1OWNER_FIELD_NUMBER = 13;
    private volatile java.lang.Object topic1Owner_;
    /**
     * <code>string topic1Owner = 13;</code>
     * @return The topic1Owner.
     */
    @java.lang.Override
    public java.lang.String getTopic1Owner() {
      java.lang.Object ref = topic1Owner_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic1Owner_ = s;
        return s;
      }
    }
    /**
     * <code>string topic1Owner = 13;</code>
     * @return The bytes for topic1Owner.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTopic1OwnerBytes() {
      java.lang.Object ref = topic1Owner_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic1Owner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOPIC2OWNER_FIELD_NUMBER = 14;
    private volatile java.lang.Object topic2Owner_;
    /**
     * <code>string topic2Owner = 14;</code>
     * @return The topic2Owner.
     */
    @java.lang.Override
    public java.lang.String getTopic2Owner() {
      java.lang.Object ref = topic2Owner_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic2Owner_ = s;
        return s;
      }
    }
    /**
     * <code>string topic2Owner = 14;</code>
     * @return The bytes for topic2Owner.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTopic2OwnerBytes() {
      java.lang.Object ref = topic2Owner_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic2Owner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, topic_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(3, content_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, senderName_);
      }
      if (senderId_ != 0) {
        output.writeInt32(5, senderId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, type_);
      }
      if (startingPosition_ != 0) {
        output.writeInt32(7, startingPosition_);
      }
      if (requiredMsgCount_ != 0) {
        output.writeInt32(8, requiredMsgCount_);
      }
      if (copyNum_ != 0) {
        output.writeInt32(9, copyNum_);
      }
      if (leaderId_ != 0) {
        output.writeInt32(10, leaderId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dataVersion_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, dataVersion_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(subscriber_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, subscriber_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic1Owner_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, topic1Owner_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic2Owner_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, topic2Owner_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, topic_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, content_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, senderName_);
      }
      if (senderId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, senderId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, type_);
      }
      if (startingPosition_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, startingPosition_);
      }
      if (requiredMsgCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, requiredMsgCount_);
      }
      if (copyNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, copyNum_);
      }
      if (leaderId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, leaderId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dataVersion_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, dataVersion_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(subscriber_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, subscriber_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic1Owner_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, topic1Owner_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic2Owner_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, topic2Owner_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MsgInfo.Msg)) {
        return super.equals(obj);
      }
      MsgInfo.Msg other = (MsgInfo.Msg) obj;

      if (getId()
          != other.getId()) return false;
      if (!getTopic()
          .equals(other.getTopic())) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!getSenderName()
          .equals(other.getSenderName())) return false;
      if (getSenderId()
          != other.getSenderId()) return false;
      if (!getType()
          .equals(other.getType())) return false;
      if (getStartingPosition()
          != other.getStartingPosition()) return false;
      if (getRequiredMsgCount()
          != other.getRequiredMsgCount()) return false;
      if (getCopyNum()
          != other.getCopyNum()) return false;
      if (getLeaderId()
          != other.getLeaderId()) return false;
      if (!getDataVersion()
          .equals(other.getDataVersion())) return false;
      if (!getSubscriber()
          .equals(other.getSubscriber())) return false;
      if (!getTopic1Owner()
          .equals(other.getTopic1Owner())) return false;
      if (!getTopic2Owner()
          .equals(other.getTopic2Owner())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + TOPIC_FIELD_NUMBER;
      hash = (53 * hash) + getTopic().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + SENDERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSenderName().hashCode();
      hash = (37 * hash) + SENDERID_FIELD_NUMBER;
      hash = (53 * hash) + getSenderId();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + STARTINGPOSITION_FIELD_NUMBER;
      hash = (53 * hash) + getStartingPosition();
      hash = (37 * hash) + REQUIREDMSGCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getRequiredMsgCount();
      hash = (37 * hash) + COPYNUM_FIELD_NUMBER;
      hash = (53 * hash) + getCopyNum();
      hash = (37 * hash) + LEADERID_FIELD_NUMBER;
      hash = (53 * hash) + getLeaderId();
      hash = (37 * hash) + DATAVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getDataVersion().hashCode();
      hash = (37 * hash) + SUBSCRIBER_FIELD_NUMBER;
      hash = (53 * hash) + getSubscriber().hashCode();
      hash = (37 * hash) + TOPIC1OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getTopic1Owner().hashCode();
      hash = (37 * hash) + TOPIC2OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getTopic2Owner().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MsgInfo.Msg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MsgInfo.Msg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MsgInfo.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MsgInfo.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MsgInfo.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MsgInfo.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MsgInfo.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MsgInfo.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MsgInfo.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MsgInfo.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MsgInfo.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MsgInfo.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MsgInfo.Msg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Msg)
        MsgInfo.MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MsgInfo.internal_static_Msg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MsgInfo.internal_static_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MsgInfo.Msg.class, MsgInfo.Msg.Builder.class);
      }

      // Construct using MsgInfo.Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        topic_ = "";

        content_ = com.google.protobuf.ByteString.EMPTY;

        senderName_ = "";

        senderId_ = 0;

        type_ = "";

        startingPosition_ = 0;

        requiredMsgCount_ = 0;

        copyNum_ = 0;

        leaderId_ = 0;

        dataVersion_ = "";

        subscriber_ = "";

        topic1Owner_ = "";

        topic2Owner_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MsgInfo.internal_static_Msg_descriptor;
      }

      @java.lang.Override
      public MsgInfo.Msg getDefaultInstanceForType() {
        return MsgInfo.Msg.getDefaultInstance();
      }

      @java.lang.Override
      public MsgInfo.Msg build() {
        MsgInfo.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MsgInfo.Msg buildPartial() {
        MsgInfo.Msg result = new MsgInfo.Msg(this);
        result.id_ = id_;
        result.topic_ = topic_;
        result.content_ = content_;
        result.senderName_ = senderName_;
        result.senderId_ = senderId_;
        result.type_ = type_;
        result.startingPosition_ = startingPosition_;
        result.requiredMsgCount_ = requiredMsgCount_;
        result.copyNum_ = copyNum_;
        result.leaderId_ = leaderId_;
        result.dataVersion_ = dataVersion_;
        result.subscriber_ = subscriber_;
        result.topic1Owner_ = topic1Owner_;
        result.topic2Owner_ = topic2Owner_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MsgInfo.Msg) {
          return mergeFrom((MsgInfo.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MsgInfo.Msg other) {
        if (other == MsgInfo.Msg.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getTopic().isEmpty()) {
          topic_ = other.topic_;
          onChanged();
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        if (!other.getSenderName().isEmpty()) {
          senderName_ = other.senderName_;
          onChanged();
        }
        if (other.getSenderId() != 0) {
          setSenderId(other.getSenderId());
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (other.getStartingPosition() != 0) {
          setStartingPosition(other.getStartingPosition());
        }
        if (other.getRequiredMsgCount() != 0) {
          setRequiredMsgCount(other.getRequiredMsgCount());
        }
        if (other.getCopyNum() != 0) {
          setCopyNum(other.getCopyNum());
        }
        if (other.getLeaderId() != 0) {
          setLeaderId(other.getLeaderId());
        }
        if (!other.getDataVersion().isEmpty()) {
          dataVersion_ = other.dataVersion_;
          onChanged();
        }
        if (!other.getSubscriber().isEmpty()) {
          subscriber_ = other.subscriber_;
          onChanged();
        }
        if (!other.getTopic1Owner().isEmpty()) {
          topic1Owner_ = other.topic1Owner_;
          onChanged();
        }
        if (!other.getTopic2Owner().isEmpty()) {
          topic2Owner_ = other.topic2Owner_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MsgInfo.Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MsgInfo.Msg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object topic_ = "";
      /**
       * <code>string topic = 2;</code>
       * @return The topic.
       */
      public java.lang.String getTopic() {
        java.lang.Object ref = topic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          topic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string topic = 2;</code>
       * @return The bytes for topic.
       */
      public com.google.protobuf.ByteString
          getTopicBytes() {
        java.lang.Object ref = topic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string topic = 2;</code>
       * @param value The topic to set.
       * @return This builder for chaining.
       */
      public Builder setTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        topic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string topic = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTopic() {
        
        topic_ = getDefaultInstance().getTopic();
        onChanged();
        return this;
      }
      /**
       * <code>string topic = 2;</code>
       * @param value The bytes for topic to set.
       * @return This builder for chaining.
       */
      public Builder setTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        topic_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes content = 3;</code>
       * @return The content.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>bytes content = 3;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes content = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      private java.lang.Object senderName_ = "";
      /**
       * <code>string senderName = 4;</code>
       * @return The senderName.
       */
      public java.lang.String getSenderName() {
        java.lang.Object ref = senderName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string senderName = 4;</code>
       * @return The bytes for senderName.
       */
      public com.google.protobuf.ByteString
          getSenderNameBytes() {
        java.lang.Object ref = senderName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string senderName = 4;</code>
       * @param value The senderName to set.
       * @return This builder for chaining.
       */
      public Builder setSenderName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string senderName = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderName() {
        
        senderName_ = getDefaultInstance().getSenderName();
        onChanged();
        return this;
      }
      /**
       * <code>string senderName = 4;</code>
       * @param value The bytes for senderName to set.
       * @return This builder for chaining.
       */
      public Builder setSenderNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderName_ = value;
        onChanged();
        return this;
      }

      private int senderId_ ;
      /**
       * <code>int32 senderId = 5;</code>
       * @return The senderId.
       */
      @java.lang.Override
      public int getSenderId() {
        return senderId_;
      }
      /**
       * <code>int32 senderId = 5;</code>
       * @param value The senderId to set.
       * @return This builder for chaining.
       */
      public Builder setSenderId(int value) {
        
        senderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 senderId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderId() {
        
        senderId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 6;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 6;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 6;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 6;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private int startingPosition_ ;
      /**
       * <code>int32 startingPosition = 7;</code>
       * @return The startingPosition.
       */
      @java.lang.Override
      public int getStartingPosition() {
        return startingPosition_;
      }
      /**
       * <code>int32 startingPosition = 7;</code>
       * @param value The startingPosition to set.
       * @return This builder for chaining.
       */
      public Builder setStartingPosition(int value) {
        
        startingPosition_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 startingPosition = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartingPosition() {
        
        startingPosition_ = 0;
        onChanged();
        return this;
      }

      private int requiredMsgCount_ ;
      /**
       * <code>int32 requiredMsgCount = 8;</code>
       * @return The requiredMsgCount.
       */
      @java.lang.Override
      public int getRequiredMsgCount() {
        return requiredMsgCount_;
      }
      /**
       * <code>int32 requiredMsgCount = 8;</code>
       * @param value The requiredMsgCount to set.
       * @return This builder for chaining.
       */
      public Builder setRequiredMsgCount(int value) {
        
        requiredMsgCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 requiredMsgCount = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequiredMsgCount() {
        
        requiredMsgCount_ = 0;
        onChanged();
        return this;
      }

      private int copyNum_ ;
      /**
       * <code>int32 copyNum = 9;</code>
       * @return The copyNum.
       */
      @java.lang.Override
      public int getCopyNum() {
        return copyNum_;
      }
      /**
       * <code>int32 copyNum = 9;</code>
       * @param value The copyNum to set.
       * @return This builder for chaining.
       */
      public Builder setCopyNum(int value) {
        
        copyNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 copyNum = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearCopyNum() {
        
        copyNum_ = 0;
        onChanged();
        return this;
      }

      private int leaderId_ ;
      /**
       * <code>int32 leaderId = 10;</code>
       * @return The leaderId.
       */
      @java.lang.Override
      public int getLeaderId() {
        return leaderId_;
      }
      /**
       * <code>int32 leaderId = 10;</code>
       * @param value The leaderId to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderId(int value) {
        
        leaderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 leaderId = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeaderId() {
        
        leaderId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object dataVersion_ = "";
      /**
       * <code>string dataVersion = 11;</code>
       * @return The dataVersion.
       */
      public java.lang.String getDataVersion() {
        java.lang.Object ref = dataVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dataVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dataVersion = 11;</code>
       * @return The bytes for dataVersion.
       */
      public com.google.protobuf.ByteString
          getDataVersionBytes() {
        java.lang.Object ref = dataVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dataVersion = 11;</code>
       * @param value The dataVersion to set.
       * @return This builder for chaining.
       */
      public Builder setDataVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dataVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dataVersion = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataVersion() {
        
        dataVersion_ = getDefaultInstance().getDataVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string dataVersion = 11;</code>
       * @param value The bytes for dataVersion to set.
       * @return This builder for chaining.
       */
      public Builder setDataVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dataVersion_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object subscriber_ = "";
      /**
       * <code>string subscriber = 12;</code>
       * @return The subscriber.
       */
      public java.lang.String getSubscriber() {
        java.lang.Object ref = subscriber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          subscriber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string subscriber = 12;</code>
       * @return The bytes for subscriber.
       */
      public com.google.protobuf.ByteString
          getSubscriberBytes() {
        java.lang.Object ref = subscriber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subscriber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string subscriber = 12;</code>
       * @param value The subscriber to set.
       * @return This builder for chaining.
       */
      public Builder setSubscriber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        subscriber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string subscriber = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearSubscriber() {
        
        subscriber_ = getDefaultInstance().getSubscriber();
        onChanged();
        return this;
      }
      /**
       * <code>string subscriber = 12;</code>
       * @param value The bytes for subscriber to set.
       * @return This builder for chaining.
       */
      public Builder setSubscriberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        subscriber_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object topic1Owner_ = "";
      /**
       * <code>string topic1Owner = 13;</code>
       * @return The topic1Owner.
       */
      public java.lang.String getTopic1Owner() {
        java.lang.Object ref = topic1Owner_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          topic1Owner_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string topic1Owner = 13;</code>
       * @return The bytes for topic1Owner.
       */
      public com.google.protobuf.ByteString
          getTopic1OwnerBytes() {
        java.lang.Object ref = topic1Owner_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topic1Owner_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string topic1Owner = 13;</code>
       * @param value The topic1Owner to set.
       * @return This builder for chaining.
       */
      public Builder setTopic1Owner(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        topic1Owner_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string topic1Owner = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearTopic1Owner() {
        
        topic1Owner_ = getDefaultInstance().getTopic1Owner();
        onChanged();
        return this;
      }
      /**
       * <code>string topic1Owner = 13;</code>
       * @param value The bytes for topic1Owner to set.
       * @return This builder for chaining.
       */
      public Builder setTopic1OwnerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        topic1Owner_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object topic2Owner_ = "";
      /**
       * <code>string topic2Owner = 14;</code>
       * @return The topic2Owner.
       */
      public java.lang.String getTopic2Owner() {
        java.lang.Object ref = topic2Owner_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          topic2Owner_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string topic2Owner = 14;</code>
       * @return The bytes for topic2Owner.
       */
      public com.google.protobuf.ByteString
          getTopic2OwnerBytes() {
        java.lang.Object ref = topic2Owner_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topic2Owner_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string topic2Owner = 14;</code>
       * @param value The topic2Owner to set.
       * @return This builder for chaining.
       */
      public Builder setTopic2Owner(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        topic2Owner_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string topic2Owner = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearTopic2Owner() {
        
        topic2Owner_ = getDefaultInstance().getTopic2Owner();
        onChanged();
        return this;
      }
      /**
       * <code>string topic2Owner = 14;</code>
       * @param value The bytes for topic2Owner to set.
       * @return This builder for chaining.
       */
      public Builder setTopic2OwnerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        topic2Owner_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Msg)
    }

    // @@protoc_insertion_point(class_scope:Msg)
    private static final MsgInfo.Msg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MsgInfo.Msg();
    }

    public static MsgInfo.Msg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Msg>
        PARSER = new com.google.protobuf.AbstractParser<Msg>() {
      @java.lang.Override
      public Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Msg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Msg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MsgInfo.Msg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Msg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmsg.proto\"\217\002\n\003Msg\022\n\n\002id\030\001 \001(\005\022\r\n\005topic" +
      "\030\002 \001(\t\022\017\n\007content\030\003 \001(\014\022\022\n\nsenderName\030\004 " +
      "\001(\t\022\020\n\010senderId\030\005 \001(\005\022\014\n\004type\030\006 \001(\t\022\030\n\020s" +
      "tartingPosition\030\007 \001(\005\022\030\n\020requiredMsgCoun" +
      "t\030\010 \001(\005\022\017\n\007copyNum\030\t \001(\005\022\020\n\010leaderId\030\n \001" +
      "(\005\022\023\n\013dataVersion\030\013 \001(\t\022\022\n\nsubscriber\030\014 " +
      "\001(\t\022\023\n\013topic1Owner\030\r \001(\t\022\023\n\013topic2Owner\030" +
      "\016 \001(\tB\tB\007MsgInfob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Msg_descriptor,
        new java.lang.String[] { "Id", "Topic", "Content", "SenderName", "SenderId", "Type", "StartingPosition", "RequiredMsgCount", "CopyNum", "LeaderId", "DataVersion", "Subscriber", "Topic1Owner", "Topic2Owner", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
